---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:18.04.0-ce
    privileged: true
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - auto/build.sh

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
